=== gnu-user/sugar-nanny/api/json/schemas/requests/account_signup.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "type": "object",

    "properties":
    {
        "first_name":          { "type": "string" },
        "last_name":           { "type": "string" },
        "email":               { "type": "string", "format": "email", "pattern": "^[^@]+@[^@]+$" },
        "password":            { "type": "string" },
        "height":              { "type": "number" },
        "weight":              { "type": "number" },
        "sex":                 { "type": "string" },
        "dob":                 { "type": "string", "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$" },
        "diabetes_type":       { "type": "integer"},
        "high_blood_pressure": { "type": "boolean"},
        "pregnant":            { "type": "boolean"},
        "insulin_tdd":         { "type": "number" },
        "background_dose":     { "type": "number" },
        "pre_meal_target":     { "type": "number" },
        "post_meal_target":    { "type": "number" }
    },
    "required": ["first_name", "last_name", "email", "password",
                 "height", "weight", "sex", "dob", "diabetes_type",
                 "high_blood_pressure", "pregnant", "insulin_tdd",
                 "background_dose", "pre_meal_target", "post_meal_target"]
}

=== gnu-user/sugar-nanny/api/signup.json
{
        "first_name":  "Jonathan",
        "last_name":   "Gillett",
        "email":       "hello5@gmail.com",
        "password":    "test",
        "height":      1.9,    
        "weight":      90.7,  
        "sex":         "M",
        "dob":         "1990-05-17",
        "diabetes_type": 1,
        "high_blood_pressure": false, 
        "pregnant": false,
        "insulin_tdd": 34,    
        "background_dose": 2,     
        "pre_meal_target": 6.2,  
        "post_meal_target": 8.9
}
